// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCustomFilterLists() {
  return window['go']['app']['App']['ExportCustomFilterLists']();
}

export function ExportLocalResourcesMappings() {
  return window['go']['app']['App']['ExportLocalResourcesMappings']();
}

export function GetLocalResourcesLibraries() {
  return window['go']['app']['App']['GetLocalResourcesLibraries']();
}

export function GetLocalResourcesSettings() {
  return window['go']['app']['App']['GetLocalResourcesSettings']();
}

export function GetLocalResourcesStats() {
  return window['go']['app']['App']['GetLocalResourcesStats']();
}

export function ImportCustomFilterLists() {
  return window['go']['app']['App']['ImportCustomFilterLists']();
}

export function ImportLocalResourcesMappings() {
  return window['go']['app']['App']['ImportLocalResourcesMappings']();
}

export function IsNoSelfUpdate() {
  return window['go']['app']['App']['IsNoSelfUpdate']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['app']['App']['OnSecondInstanceLaunch'](arg1);
}

export function OpenLogsDirectory() {
  return window['go']['app']['App']['OpenLogsDirectory']();
}

export function ResetLocalResourcesStats() {
  return window['go']['app']['App']['ResetLocalResourcesStats']();
}

export function RestartApplication() {
  return window['go']['app']['App']['RestartApplication']();
}

export function SelectAppForRouting() {
  return window['go']['app']['App']['SelectAppForRouting']();
}

export function SetLocalResourcesBlockMissing(arg1) {
  return window['go']['app']['App']['SetLocalResourcesBlockMissing'](arg1);
}

export function SetLocalResourcesCustomDir(arg1) {
  return window['go']['app']['App']['SetLocalResourcesCustomDir'](arg1);
}

export function SetLocalResourcesEnabled(arg1) {
  return window['go']['app']['App']['SetLocalResourcesEnabled'](arg1);
}

export function SetLocalResourcesLibraryEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetLocalResourcesLibraryEnabled'](arg1, arg2);
}

export function StartProxy() {
  return window['go']['app']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['app']['App']['StopProxy']();
}

export function UninstallCA() {
  return window['go']['app']['App']['UninstallCA']();
}
