// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {localcdn} from '../models';
import {config} from '../models';
import {options} from '../models';

export function ExportCustomFilterLists():Promise<void>;

export function ExportLocalResourcesMappings():Promise<void>;

export function GetLocalResourcesLibraries():Promise<Array<localcdn.LibraryInfo>>;

export function GetLocalResourcesSettings():Promise<config.LocalResources>;

export function GetLocalResourcesStats():Promise<config.LocalResourcesStats>;

export function ImportCustomFilterLists():Promise<void>;

export function ImportLocalResourcesMappings():Promise<void>;

export function IsNoSelfUpdate():Promise<boolean>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function OpenLogsDirectory():Promise<void>;

export function ResetLocalResourcesStats():Promise<void>;

export function RestartApplication():Promise<void>;

export function SelectAppForRouting():Promise<string>;

export function SetLocalResourcesBlockMissing(arg1:boolean):Promise<void>;

export function SetLocalResourcesCustomDir(arg1:string):Promise<void>;

export function SetLocalResourcesEnabled(arg1:boolean):Promise<void>;

export function SetLocalResourcesLibraryEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function UninstallCA():Promise<void>;
